plugins { id 'com.android.application' }

android {
    namespace 'cn.coco.ssrelay'
    compileSdk 35

    defaultConfig {
        applicationId 'cn.coco.ssrelay'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '0.4.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        resources {
            excludes += 'META-INF/versions/**'
        }
    }
}

dependencies {
    implementation 'com.github.mwiede:jsch:0.2.21'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
}
